name: .NET 9 CI/CD

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore Movies.sln
      
    - name: Build
      run: dotnet build Movies.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test Movies.sln --configuration Release --no-build
      



