name: .NET 9 CI/CD

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore Movies.sln
      
    - name: Build
      run: dotnet build Movies.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test Movies.sln --configuration Release --no-build --verbosity normal
      
    - name: Code Quality - Run Code Analysis
      run: |
        dotnet tool install --global dotnet-format
        
        # Run code formatting check
        dotnet format Movies.sln --verify-no-changes --verbosity diagnostic

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Install security scanning tools
      run: |
        dotnet tool install --global dotnet-security-scanner
        
    - name: Run Security Scan
      run: |
        # Scan NuGet packages for vulnerabilities
        dotnet list Movies.sln package --vulnerable --include-transitive

